###
POST https://localhost:7071/auth/login
Content-Type: application/json

{
    "identity": "CHAVA",
    "key": "CHAVA"
}

###
GET https://localhost:7071/message
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjJiNWU3YjdjLTQ5MTItNDA3Zi04YjJmLTQ0NDYwYjhhM2M2ZSIsIklkZW50aXR5IjoiQ0hBVkEiLCJQZXJtaXNzaW9uIjpbIk1BTkFHRV9DUkVERU5USUFMIiwiUkVBRF9QRVJNSVNTSU9OIiwiUkVBRF9NRVNTQUdFIiwiTUFOQUdFX1BFUk1JU1NJT04iLCJNQU5BR0VfTUVTU0FHRSIsIlJFQURfQ1JFREVOVElBTF9QRVJNSVNTSU9OIiwiTUFOQUdFX0NSRURFTlRJQUxfUEVSTUlTU0lPTiIsIlJFQURfQ1JFREVOVElBTCJdLCJuYmYiOjE2ODc1NTIwMDcsImV4cCI6MTY4NzU1MzIwNywiaWF0IjoxNjg3NTUyMDA3fQ.vp_gvie2jdEFHKpXw8R9UMRgNimq49BhVK7Fd1aVzs8


###
GET https://localhost:7071/message/page?hint=B
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjJiNWU3YjdjLTQ5MTItNDA3Zi04YjJmLTQ0NDYwYjhhM2M2ZSIsIklkZW50aXR5IjoiQ0hBVkEiLCJQZXJtaXNzaW9uIjpbIk1BTkFHRV9DUkVERU5USUFMIiwiUkVBRF9QRVJNSVNTSU9OIiwiUkVBRF9NRVNTQUdFIiwiTUFOQUdFX1BFUk1JU1NJT04iLCJNQU5BR0VfTUVTU0FHRSIsIlJFQURfQ1JFREVOVElBTF9QRVJNSVNTSU9OIiwiTUFOQUdFX0NSRURFTlRJQUxfUEVSTUlTU0lPTiIsIlJFQURfQ1JFREVOVElBTCJdLCJuYmYiOjE2ODc1NTIwMDcsImV4cCI6MTY4NzU1MzIwNywiaWF0IjoxNjg3NTUyMDA3fQ.vp_gvie2jdEFHKpXw8R9UMRgNimq49BhVK7Fd1aVzs8

###
POST https://localhost:7071/message
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjJiNWU3YjdjLTQ5MTItNDA3Zi04YjJmLTQ0NDYwYjhhM2M2ZSIsIklkZW50aXR5IjoiQ0hBVkEiLCJQZXJtaXNzaW9uIjpbIk1BTkFHRV9DUkVERU5USUFMIiwiUkVBRF9QRVJNSVNTSU9OIiwiUkVBRF9NRVNTQUdFIiwiTUFOQUdFX1BFUk1JU1NJT04iLCJNQU5BR0VfTUVTU0FHRSIsIlJFQURfQ1JFREVOVElBTF9QRVJNSVNTSU9OIiwiTUFOQUdFX0NSRURFTlRJQUxfUEVSTUlTU0lPTiIsIlJFQURfQ1JFREVOVElBTCJdLCJuYmYiOjE2ODc0NzQ0NzMsImV4cCI6MTY4NzQ3NTY3MywiaWF0IjoxNjg3NDc0NDczfQ.KNc2OIA7RO-fbUNtpyQzGKJIInSpHgvExwKBu5afDLQ
Content-Type: application/json

{
    "sender": "CHAVA",
    "receiver": "MANU",
    "content": "TEXT MESSAGE"
}

###
PUT https://localhost:7071/message/43e9c18d-2d7c-4550-9c41-c30df7874630
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjJiNWU3YjdjLTQ5MTItNDA3Zi04YjJmLTQ0NDYwYjhhM2M2ZSIsIklkZW50aXR5IjoiQ0hBVkEiLCJQZXJtaXNzaW9uIjpbIk1BTkFHRV9DUkVERU5USUFMIiwiUkVBRF9QRVJNSVNTSU9OIiwiUkVBRF9NRVNTQUdFIiwiTUFOQUdFX1BFUk1JU1NJT04iLCJNQU5BR0VfTUVTU0FHRSIsIlJFQURfQ1JFREVOVElBTF9QRVJNSVNTSU9OIiwiTUFOQUdFX0NSRURFTlRJQUxfUEVSTUlTU0lPTiIsIlJFQURfQ1JFREVOVElBTCJdLCJuYmYiOjE2ODc0NzQ0NzMsImV4cCI6MTY4NzQ3NTY3MywiaWF0IjoxNjg3NDc0NDczfQ.KNc2OIA7RO-fbUNtpyQzGKJIInSpHgvExwKBu5afDLQ
Content-Type: application/json

{
    "sender": "CHAVA",
    "receiver": "MANU",
    "content": "TEXT MESSAGE CHANGED"
}