###
POST https://localhost:7071/auth/login
Content-Type: application/json

{
    "identity": "CHAVA",
    "key": "CHAVA"
}

###
GET https://localhost:7071/message/page
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjJiNWU3YjdjLTQ5MTItNDA3Zi04YjJmLTQ0NDYwYjhhM2M2ZSIsIklkZW50aXR5IjoiQ0hBVkEiLCJQZXJtaXNzaW9uIjpbIk1BTkFHRV9DUkVERU5USUFMIiwiUkVBRF9QRVJNSVNTSU9OIiwiUkVBRF9NRVNTQUdFIiwiTUFOQUdFX1BFUk1JU1NJT04iLCJNQU5BR0VfTUVTU0FHRSIsIlJFQURfQ1JFREVOVElBTF9QRVJNSVNTSU9OIiwiTUFOQUdFX0NSRURFTlRJQUxfUEVSTUlTU0lPTiIsIlJFQURfQ1JFREVOVElBTCJdLCJuYmYiOjE2ODc0NDQ5MjgsImV4cCI6MTY4NzQ0NjEyOCwiaWF0IjoxNjg3NDQ0OTI4fQ.oCDpwEz5kjBCPkXoa2BgXneDO_3CVQmV1BwPi0CJ9xw

###
POST https://localhost:7071/message
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjJiNWU3YjdjLTQ5MTItNDA3Zi04YjJmLTQ0NDYwYjhhM2M2ZSIsIklkZW50aXR5IjoiQ0hBVkEiLCJQZXJtaXNzaW9uIjpbIk1BTkFHRV9DUkVERU5USUFMIiwiUkVBRF9QRVJNSVNTSU9OIiwiUkVBRF9NRVNTQUdFIiwiTUFOQUdFX1BFUk1JU1NJT04iLCJNQU5BR0VfTUVTU0FHRSIsIlJFQURfQ1JFREVOVElBTF9QRVJNSVNTSU9OIiwiTUFOQUdFX0NSRURFTlRJQUxfUEVSTUlTU0lPTiIsIlJFQURfQ1JFREVOVElBTCJdLCJuYmYiOjE2ODc0NDQ5MjgsImV4cCI6MTY4NzQ0NjEyOCwiaWF0IjoxNjg3NDQ0OTI4fQ.oCDpwEz5kjBCPkXoa2BgXneDO_3CVQmV1BwPi0CJ9xw
Content-Type: application/json

{
    "sender": "CHAVA",
    "receiver": "MANU",
    "content": "TEXT MESSAGE"
}

###
PUT https://localhost:7071/message/43e9c18d-2d7c-4550-9c41-c30df7874630
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjJiNWU3YjdjLTQ5MTItNDA3Zi04YjJmLTQ0NDYwYjhhM2M2ZSIsIklkZW50aXR5IjoiQ0hBVkEiLCJQZXJtaXNzaW9uIjpbIk1BTkFHRV9DUkVERU5USUFMIiwiUkVBRF9QRVJNSVNTSU9OIiwiUkVBRF9NRVNTQUdFIiwiTUFOQUdFX1BFUk1JU1NJT04iLCJNQU5BR0VfTUVTU0FHRSIsIlJFQURfQ1JFREVOVElBTF9QRVJNSVNTSU9OIiwiTUFOQUdFX0NSRURFTlRJQUxfUEVSTUlTU0lPTiIsIlJFQURfQ1JFREVOVElBTCJdLCJuYmYiOjE2ODc0NDQ5MjgsImV4cCI6MTY4NzQ0NjEyOCwiaWF0IjoxNjg3NDQ0OTI4fQ.oCDpwEz5kjBCPkXoa2BgXneDO_3CVQmV1BwPi0CJ9xw
Content-Type: application/json

{
    "sender": "CHAVA",
    "receiver": "MANU",
    "content": "TEXT MESSAGE CHANGED"
}