###
POST https://localhost:7181/auth/login
Content-Type: application/json

{
    "identity": "CHAVA",
    "key": "CHAVA"
}

###
GET https://localhost:7181/message
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjJiNWU3YjdjLTQ5MTItNDA3Zi04YjJmLTQ0NDYwYjhhM2M2ZSIsIklkZW50aXR5IjoiQ0hBVkEiLCJQZXJtaXNzaW9uIjpbIk1BTkFHRV9DUkVERU5USUFMIiwiTUFOQUdFX0NSRURFTlRJQUxfUEVSTUlTU0lPTiIsIk1BTkFHRV9NRVNTQUdFIiwiTUFOQUdFX1BFUk1JU1NJT04iLCJSRUFEX0NSRURFTlRJQUwiLCJSRUFEX1BFUk1JU1NJT04iXSwibmJmIjoxNjg3OTgwODY4LCJleHAiOjE2ODc5ODIwNjgsImlhdCI6MTY4Nzk4MDg2OH0.0F40heur4dS6N7pegwpS_yesn7ue725kavf0KiM0gqE



